name: Test code with pytest unit tests
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Installing dependencies
        uses: actions/setup-python@main
        with:
          python-version: '3.11'
      - name: Installing pytest
        run: pip install -U pytest
      - name: Installing flask
        run: pip install Flask[async]
      - name: Installing flask-login
        run: pip install Flask-Login
      - name: Installing pypdf
        run: pip install pypdf
      - name: Cloning repo
        uses: actions/checkout@main
      - name: Creating database
        run: python database/create_db.py
      - name: Testing
        run: echo "Testing code..."
      - run: python -m pytest test*
